version: 0.2

phases:

  install:

    runtime-versions: 
      dotnet: 2.2
      nodejs: 10

    commands:
      - echo "Installing CDK..."
      - npm install -g aws-cdk

      - echo "Installing AWS extensions for .NET Core..."
      - dotnet tool install -g Amazon.Lambda.Tools

  pre_build:
    commands:
      - echo "Running tests..."
      - dotnet test

  build:
    commands:
      - echo "Building lambda source..."
      - dotnet lambda package -pl lambda-src/Cambria.BAM.DevOpsTalk.Api.Lambda

      - echo "Building CDK source..."
      - dotnet build src/CambriaBamDevOpsTalkApi

      - echo "Synthesizing Cloudformation from CDK project..."
      - cdk synth
  
  post_build:
    commands:
      - echo "Deploying stack..."
      - cdk deploy
